# Site settings
title: Considered Design
email: dominic@smartsparrow.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description. Work in progress...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://considered.design" # the base hostname & protocol for your site
twitter_username: dominosebastian
github_username:  domseb


# Build settings
markdown: kramdown

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/

gems:
  - jekyll-assets
  - octopress-autoprefixer

navigation:
  - title: work
    url: /work/
  - title: about
    url: /about/
  - title: writing
    url: /writing/
